apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellojib-test
spec:
  selector:
    matchLabels:
      app: hellojib-test
  template:
    metadata:
      labels:
        app: hellojba-test
    spec:
      containers:
      - name: hellojib-java
        image: registry.cn-shenzhen.aliyuncs.com/olight-devops/hellojib:${TAG}
        imagePullPolicy: Always
