apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-java
  labels:
    app: test-java
spec:
  selector:
    matchLabels:
      app: test-java
  template:
    metadata:
      labels:
        app: test-java
    spec:
      containers:
      - name: test-java
        image: registry.cn-shenzhen.aliyuncs.com/olight-devops/hellojib:${TAG}
        imagePullPolicy: Always
